# This is a basic workflow to help you get started with Actions

name: PHP-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  tests:

    name: PHP-Unit
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Validate composer.json and composer.lock
        run: composer validate --strict || composer update

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - run: pwd
      - run: ls

      - name: Run test suite
        env:
            XDEBUG_MODE: coverage
        run: composer run-script test

      - name: Prepare for SonarCloud Scan - sed on clover.xml
        run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace@g' build/clover.xml

      - name: Prepare for SonarCloud Scan - sed on junit.xml
        run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace@g' build/junit.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
